site_name: Crawl, Walk, Run, Autmoate - Nik Charlebois' Blog
site_url: https://nikcharlebois.github.io/Nik-Charlebois.com/
nav:
  - Home:
      - 'Introduction': 'index.md'
      - 'What is Microsoft365DSC?': 'home/what-is-M365DSC.md'
  - Blog:
      - 'Blog Posts': 'blog/index.md'
  - About:
      - 'Why Microsoft365DSC': 'about/why.md'
      - 'Changelog': https://github.com/microsoft/Microsoft365DSC/blob/master/CHANGELOG.md" target="_blank
      - 'License': 'about/license.md'
      - 'Community Resources': 'about/community-resources.md'
plugins:
  - search
  - include_dir_to_nav
theme:
  name: 'dracula'
  custom_dir: docs/overrides
  logo: Images/SmallLogo.png
  favicon: Images/favicon.ico
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - search.share
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 0
  - def_list
  - attr_list
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/Microsoft365DSC'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/channel/UCveScabVT6pxzqYgGRu17iw'
    - icon: fontawesome/solid/link
      link: 'https://www.powershellgallery.com/packages/Microsoft365DSC/'
  generator: false
  analytics:
    provider: google
    property: UA-246073771-1
extra_css:
  - stylesheets/extra.css
edit_uri: tree/Dev/docs/docs
copyright: Microsoft365DSC
