site_name: Nik Charlebois - Crawl, Walk, Run, Automate
site_url: https://nikcharlebois.github.io/Nik-Charlebois.com/
nav:
  - Home: 'index.md'
  - About Me: 'about.md'
plugins:
  - search
  - include_dir_to_nav
theme:
  name: 'material'
  custom_dir: docs/overrides
  logo: /Images/logo.png
  favicon: Images/favicon.ico
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - search.share
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 0
  - def_list
  - attr_list
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/NikCharlebois'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/channel/UCveScabVT6pxzqYgGRu17iw'
    - icon: fontawesome/solid/linkedin
      link: 'https://www.linkedin.com/in/nikcharlebois/'
  generator: false
  analytics:
    provider: google
    property: G-G3L4JDZK7N
extra_css:
  - stylesheets/extra.css
edit_uri: tree/Dev/docs/docs
copyright: Nik Charlebois
