name: Generate Resources & Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write

    # Only when run from the main repo
    if: github.repository == 'NikCharlebois/Nik-Charlebois.com'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.GenerateResource.outputs.commitid }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-dracula-theme
          pip install mkdocs-include-dir-to-nav
      - name: Deploy
        working-directory: ./docs
        run: mkdocs gh-deploy --force
